### ISSUE TITLE
Add 'incrementor' example for Solana

### ISSUE THREAD

**Issue by cyphersnake** [debridge-finance/debridge-solana-sdk#19]
@merrymari please provide all details, what you have about this task or tag someone who can provide it

**Comment by aravinddojima** [comment]
I don't see an clear example of solana+EVM contracts in this repo [

> https://github.com/debridge-finance/debridge-cross-chain-dapp-example

], Can someone help me to spot the repo which consist of the above example(cross-chain example for solana+EVM) ?

**Comment by cyphersnake** [comment]
@aravinddojima Yes, the example is ready only from Solana side, to get the code from EVM side you need to tag @merrymari

**Comment by devDesu** [comment]
Hi @aravinddojima! Please join our [discord](https://discord.gg/M5EDjc3X) server and ask your questions in dev channel so we can help you
